### ISSUE TITLE
Lighttpd.service error

### ISSUE THREAD

**Issue by Mo0nShad3** [theonemule/azure-blog-storage-ftp-server#2]
Hi there, I have found your repo detailing how to setup a ftp server using azure blob storage and I am having an issue with the lighttpd.service where I am getting this error:
Job for lighttpd.service failed because the control process exited with error code.
See "systemctl status lighttpd.service" and "journalctl -xeu lighttpd.service" for details.

It does not seem to be able to start the service.

Any help is appreciated.
Thanks

**Comment by theonemule** [comment]
Ooh... I haven't touched this in a LONG time. I wouldn't use this. Instead, use the native support for FTP on blob storage.

https://learn.microsoft.com/en-us/azure/storage/blobs/secure-file-transfer-protocol-support

**Comment by gstrauss** [comment]
> See "systemctl status lighttpd.service" and "journalctl -xeu lighttpd.service" for details.

> Any help is appreciated.

See above
